justice_league = ["Superman", "Batman", "Wonder Woman", "Flash", "Aquaman", "Green Lantern"]
print("Initial Justice League:", justice_league)
print("\n")
number_of_members = len(justice_league)
print("Number of members in the Justice League:", number_of_members)
print("\n")
justice_league.extend(["Batgirl", "Nightwing"])
print("Justice League after adding Batgirl and Nightwing:")
print(justice_league)
print("\n")
justice_league.remove("Wonder Woman")
justice_league.insert(0, "Wonder Woman")
print("Justice League with Wonder Woman as the leader:")
print(justice_league)
print("\n")
justice_league.remove("Green Lantern")  # I chose to move Green Lantern
justice_league.insert(justice_league.index("Aquaman") + 1, "Green Lantern")
print("Justice League with Green Lantern between Aquaman and Flash:")
print(justice_league)
print("\n")
justice_league = ["Cyborg", "Shazam", "Hawkgirl", "Martian Manhunter", "Green Arrow"]
print("Justice League after Superman assembles a new team:")
print(justice_league)
print("\n")
justice_league.sort()
print("Justice League sorted alphabetically with the new leader:")
print(justice_league)
